//
//  GreenTheme.swift
//  MealPrepIOSApp
//
//  Created by AI Assistant on 7/26/25.
//  Green color theme for unified app experience
//

import SwiftUI

// MARK: - Green Theme Colors
extension Color {
    // Note: primaryGreen, secondaryGreen, tertiaryGreen, and greenBackground 
    // are auto-generated by Xcode from Assets.xcassets
    
    // Additional green theme variations
    static let greenTint = Color(red: 0.255, green: 0.686, blue: 0.153)
    static let lightGreen = Color(red: 0.400, green: 0.800, blue: 0.200)
    static let darkGreen = Color(red: 0.180, green: 0.520, blue: 0.100)
    
    // Semantic colors for green theme
    static let success = primaryGreen
    static let successBackground = Color(red: 0.940, green: 0.980, blue: 0.950)
    static let warning = Color(red: 0.980, green: 0.686, blue: 0.153)
    static let error = Color(red: 0.980, green: 0.255, blue: 0.153)
}

// MARK: - Green Theme Gradients
extension LinearGradient {
    static let primaryGreenGradient = LinearGradient(
        colors: [Color.primaryGreen, Color.lightGreen],
        startPoint: .topLeading,
        endPoint: .bottomTrailing
    )
    
    static let subtleGreenGradient = LinearGradient(
        colors: [Color.greenBackground, Color.greenBackground.opacity(0.8)],
        startPoint: .topLeading,
        endPoint: .bottomTrailing
    )
    
    static let greenCardGradient = LinearGradient(
        colors: [
            Color(.systemBackground),
            Color.greenBackground.opacity(0.3)
        ],
        startPoint: .topLeading,
        endPoint: .bottomTrailing
    )
}

// MARK: - Green Theme Button Styles
struct GreenThemeButtonStyle: ButtonStyle {
    let style: ButtonVariant
    
    enum ButtonVariant {
        case primary, secondary, outline, subtle
    }
    
    func makeBody(configuration: Configuration) -> some View {
        configuration.label
            .font(.headline)
            .fontWeight(.semibold)
            .foregroundColor(textColor)
            .frame(maxWidth: .infinity, minHeight: 50)
            .background(backgroundView)
            .scaleEffect(configuration.isPressed ? 0.95 : 1.0)
            .animation(.easeInOut(duration: 0.1), value: configuration.isPressed)
    }
    
    private var textColor: Color {
        switch style {
        case .primary: return .white
        case .secondary: return .primaryGreen
        case .outline: return .primaryGreen
        case .subtle: return .primary
        }
    }
    
    private var backgroundView: some View {
        RoundedRectangle(cornerRadius: 12)
            .fill(backgroundColor)
            .overlay(
                RoundedRectangle(cornerRadius: 12)
                    .stroke(borderColor, lineWidth: borderWidth)
            )
    }
    
    private var backgroundColor: Color {
        switch style {
        case .primary: return .primaryGreen
        case .secondary: return .greenBackground
        case .outline: return .clear
        case .subtle: return Color(.systemGray6)
        }
    }
    
    private var borderColor: Color {
        switch style {
        case .primary: return .clear
        case .secondary: return .clear
        case .outline: return .primaryGreen
        case .subtle: return .clear
        }
    }
    
    private var borderWidth: CGFloat {
        style == .outline ? 1 : 0
    }
}

// MARK: - Green Theme Card Style
struct GreenMagicCard<Content: View>: View {
    let content: Content
    let cornerRadius: CGFloat
    let shadowRadius: CGFloat
    
    init(cornerRadius: CGFloat = 16, shadowRadius: CGFloat = 8, @ViewBuilder content: () -> Content) {
        self.content = content()
        self.cornerRadius = cornerRadius
        self.shadowRadius = shadowRadius
    }
    
    var body: some View {
        ZStack {
            // Background with green-themed gradient
            RoundedRectangle(cornerRadius: cornerRadius)
                .fill(LinearGradient.greenCardGradient)
                .background(
                    RoundedRectangle(cornerRadius: cornerRadius)
                        .fill(Color.primaryGreen.opacity(0.05))
                )
                .shadow(
                    color: Color.primaryGreen.opacity(0.15),
                    radius: shadowRadius,
                    x: 0,
                    y: 4
                )
            
            content
                .padding()
        }
    }
}

// MARK: - Green Theme Text Field Style
struct GreenTextFieldStyle: TextFieldStyle {
    @FocusState private var isFocused: Bool
    
    func _body(configuration: TextField<Self._Label>) -> some View {
        configuration
            .font(.body)
            .padding(.horizontal, 16)
            .padding(.vertical, 12)
            .background(
                RoundedRectangle(cornerRadius: 12)
                    .fill(Color.greenBackground.opacity(0.3))
                    .stroke(
                        isFocused ? Color.primaryGreen : Color.clear,
                        lineWidth: isFocused ? 2 : 0
                    )
            )
            .focused($isFocused)
    }
}

// MARK: - Convenience View Modifiers
extension View {
    func greenThemeCard(cornerRadius: CGFloat = 16, shadowRadius: CGFloat = 8) -> some View {
        GreenMagicCard(cornerRadius: cornerRadius, shadowRadius: shadowRadius) {
            self
        }
    }
    
    func primaryGreenButton() -> some View {
        self.buttonStyle(GreenThemeButtonStyle(style: .primary))
    }
    
    func secondaryGreenButton() -> some View {
        self.buttonStyle(GreenThemeButtonStyle(style: .secondary))
    }
    
    func outlineGreenButton() -> some View {
        self.buttonStyle(GreenThemeButtonStyle(style: .outline))
    }
    
    func subtleGreenButton() -> some View {
        self.buttonStyle(GreenThemeButtonStyle(style: .subtle))
    }
}